### ISSUE TITLE
Error while adding or removing Labels

### ISSUE THREAD

**Issue by Ljz7** [Lujeni/matterllo#46]
Hello, 

Following the Linux installation using pip on Debian Stretch, adding and removing labels does not work. 

Here is the traceback : 

```
[27/Dec/2017 11:06:11] "POST /callback/107/ HTTP/1.1" 500 101938
Internal Server Error: /callback/107/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/matterllo/core/views/callback.py", line 45, in post
    payload = action_parser(action=action)
  File "/opt/matterllo/core/hook/card.py", line 204, in addLabelToCard
    card = self.trello_client.get_card(data['card']['id'])
AttributeError: 'TrelloCallbacksView' object has no attribute 'trello_client'
```

Thank you.

**Comment by Lujeni** [comment]
Hello @Ljz7 

Thanks for your issue.

I'll dig this problem.

**Comment by Lujeni** [comment]
Thanks @Ljz7 

It's fixed now.
