### ISSUE TITLE
Static file not found when Debug = False

### ISSUE THREAD

**Issue by lostsnow** [Lujeni/matterllo#48]
When I change `matterllo/settings.py` with `Debug = False`, a error occurred:

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
app_1  |     self.result = application(self.environ, self.start_response)
app_1  |   File "/usr/local/lib/python2.7/site-packages/whitenoise/base.py", line 66, in __call__
app_1  |     return self.application(environ, start_response)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
app_1  |     response = self.get_response(request)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
app_1  |     response = self._middleware_chain(request)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
app_1  |     response = response_for_exception(request, exc)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
app_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
app_1  |     return callback(request, **param_dict)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
app_1  |     response = view_func(request, *args, **kwargs)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/views/defaults.py", line 74, in server_error
app_1  |     return http.HttpResponseServerError(template.render())
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
app_1  |     return self.template.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
app_1  |     return self._render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
app_1  |     return compiled_parent._render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 104, in render
app_1  |     url = self.url(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 101, in url
app_1  |     return self.handle_simple(path)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 114, in handle_simple
app_1  |     return staticfiles_storage.url(path)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in url
app_1  |     hashed_name = self.stored_name(clean_name)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 292, in stored_name
app_1  |     cache_name = self.clean_name(self.hashed_name(name))
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 95, in hashed_name
app_1  |     (clean_name, self))
app_1  | ValueError: The file 'core/img/favicon.ico' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fc508683250>.
app_1  | [11/May/2018 10:45:37] "GET /login/ HTTP/1.0" 500 59
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
app_1  |     self.result = application(self.environ, self.start_response)
app_1  |   File "/usr/local/lib/python2.7/site-packages/whitenoise/base.py", line 66, in __call__
app_1  |     return self.application(environ, start_response)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
app_1  |     response = self.get_response(request)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
app_1  |     response = self._middleware_chain(request)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
app_1  |     response = response_for_exception(request, exc)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
app_1  |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
app_1  |     return callback(request, **param_dict)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
app_1  |     response = view_func(request, *args, **kwargs)
  p_1  |   File "/usr/local/lib/python2.7/site-packages/django/views/defaults.py", line 74, in server_error
app_1  |     return http.HttpResponseServerError(template.render())
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
app_1  |     return self.template.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
app_1  |     return self._render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
app_1  |     return compiled_parent._render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 104, in render
app_1  |     url = self.url(context)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 101, in url
app_1  |     return self.handle_simple(path)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/templatetags/static.py", line 114, in handle_simple
app_1  |     return staticfiles_storage.url(path)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in url
app_1  |     hashed_name = self.stored_name(clean_name)
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 292, in stored_name
app_1  |     cache_name = self.clean_name(self.hashed_name(name))
app_1  |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 95, in hashed_name
app_1  |     (clean_name, self))
app_1  | ValueError: The file 'core/img/favicon.ico' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fc508683250>.
app_1  | [11/May/2018 10:46:54] "GET /login/ HTTP/1.0" 500 59
```

**Comment by Lujeni** [comment]
Hello @lostsnow 

Thanks for your issue.

> With debug turned off Django won't handle static files for you any more - your production web server (Apache or Nginx) should take care of that.

Tell me if you need help on your web server.
